### PR TITLE
Add an env option to limit the max number of concurrent connections

### PR DESCRIPTION
**Pull request by ggiraldez**
Setting `PROMPROXY_MAX_CONN` (default is 10) to a low value should help mitigate load on an overloaded server by serializing the proxied requests. Otherwise, promproxy will open connections to the upstream exporters as it receives scrape requests.

### CODE REVIEW

**Review by matiasgarciaisaia — APPROVED** [review]
👍

Not sure if we need the changes in dependencies, but the code looks kind of OK - not knowing Go, at least.

**Comment by ggiraldez** [comment]
> +1
> 
> Not sure if we need the changes in dependencies, but the code looks kind of OK - not knowing Go, at least.

We do need the updates because the (very) old version of x/net did not have the limit listener that this PR uses.

**Comment by ggiraldez** [comment]
One additional thing to note is that the proxy still will accept connections as they come. The limiter only works by serializing and limiting the number of active simultaneous connections. Eg. it limits the number of coroutines that handle requests.

**Comment by matiasgarciaisaia** [comment]
:shipit:

**Pull request merged**
